### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by badboy-tian** [biezhihua/FFmpegBuildTool#26]
```
export ANDROID_NDK=/Users/tian/Library/Android/sdk/ndk/23.1.7779620
export ANDROID_SDK=/Users/tian/Library/Android/sdk
```

```
./android.sh --arch-arm64-v8a 
```
error:
```
╰─➤  ./android.sh --arch-arm64-v8a  
INFO: /Users/tian/Library/Android/sdk/ndk/23.1.7779620
INFO: /Users/tian/Library/Android/sdk
INFO: Architectures:  arm64-v8a

INFO: Libraries: 

INFO: Building env_tools

Unescaped left brace in regex is passed through in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at /Users/tian/Downloads/libs-build-tool/env_tools/build/bin/automake line 3936.
INFO: Completed env tools build

INFO: Help Info

INFO: You are ready to build libs
make: `.gas' is up to date.
INFO: --------------------------------------------------------

INFO: Building arm64-v8a platform on API level 21

INFO: Starting new build for arm64-v8a on API level 21 

INFO: NDK_PATH /Users/tian/Library/Android/sdk/ndk/23.1.7779620

INFO: ARCH arm64-v8a

INFO: TOOLCHAIN darwin-x86_64

INFO: TOOLCHAIN_PATH /Users/tian/Downloads/libs-build-tool/android/ndk-toolchain-aarch64-linux-android

INFO: TOOLCHAIN_ARCH arm64

INFO: /Users/tian/Library/Android/sdk/ndk/23.1.7779620
INFO: /Users/tian/Library/Android/sdk
INFO: Building the contribs

cat: "/Users/tian/Library/Android/sdk/ndk/23.1.7779620/source.properties": No such file or directory
WARNING:__main__:make_standalone_toolchain.py is no longer necessary. The
$NDK/toolchains/llvm/prebuilt/darwin-x86_64/bin directory contains target-specific scripts that perform
the same task. For example, instead of:

    $ python $NDK/build/tools/make_standalone_toolchain.py \
        --arch arm64 --api 21 --install-dir toolchain
    $ toolchain/bin/clang++ src.cpp

Instead use:

    $ $NDK/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android21-clang++ src.cpp

Traceback (most recent call last):
  File "/Users/tian/Library/Android/sdk/ndk/23.1.7779620/build/tools/make_standalone_toolchain.py", line 377, in <module>
    main()
  File "/Users/tian/Library/Android/sdk/ndk/23.1.7779620/build/tools/make_standalone_toolchain.py", line 361, in main
    create_toolchain(install_path, args.arch, api, toolchain_path, host_tag)
  File "/Users/tian/Library/Android/sdk/ndk/23.1.7779620/build/tools/make_standalone_toolchain.py", line 224, in create_toolchain
    copy_tree(toolchain_path, install_path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dir_util.py", line 163, in copy_tree
    verbose=verbose, dry_run=dry_run))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dir_util.py", line 163, in copy_tree
    verbose=verbose, dry_run=dry_run))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dir_util.py", line 167, in copy_tree
    dry_run=dry_run)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/file_util.py", line 110, in copy_file
    "can't copy '%s': doesn't exist or not a regular file" % src)
distutils.errors.DistutilsFileError: can't copy '/Users/tian/Library/Android/sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/darwin-x86_64/aarch64-linux-android/bin/as': doesn't exist or not a regular file
```

我有点搞不懂android/common.sh
```
# 获取AndroidNDK工具链路径
get_android_toolchain_path() {
    echo ${BASEDIR}/android/ndk-toolchain-$(get_android_target_host)
}

```
工具链的路径怎么是在当前项目路径下?

**Comment by badboy-tian** [comment]
现在使用readme里面的ndk版本
```
export ANDROID_HOME=/Users/tian/Library/Android/sdk
export ANDROID_SDK=/Users/tian/Library/Android/sdk
export ANDROID_NDK=/Users/tian/Downloads/android-ndk-r18b
```

跑命令:
```
./android.sh --arch-armeabi-v7a
```
信息
```
INFO: /Users/tian/Downloads/android-ndk-r18b
INFO: /Users/tian/Library/Android/sdk
INFO: Architectures:  armeabi-v7a

INFO: Libraries: 

INFO: Building env_tools

Unescaped left brace in regex is passed through in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at /Users/tian/Downloads/libs-build-tool/env_tools/build/bin/automake line 3936.
INFO: Completed env tools build

INFO: Help Info

INFO: You are ready to build libs
make: `.gas' is up to date.
INFO: --------------------------------------------------------

INFO: Building armeabi-v7a platform on API level 21

INFO: Starting new build for armeabi-v7a on API level 21 

INFO: NDK_PATH /Users/tian/Downloads/android-ndk-r18b

INFO: ARCH armeabi-v7a

INFO: TOOLCHAIN darwin-x86_64

INFO: TOOLCHAIN_PATH /Users/tian/Downloads/libs-build-tool/android/ndk-toolchain-arm-linux-androideabi

INFO: TOOLCHAIN_ARCH arm

INFO: /Users/tian/Downloads/android-ndk-r18b
INFO: /Users/tian/Library/Android/sdk
INFO: Building the contribs

cat: "/Users/tian/Downloads/android-ndk-r18b/source.properties": No such file or directory
INFO: Building toolchain params for armeabi-v7a

INFO: PATH /usr/local/bin/:/Users/tian/Downloads/libs-build-tool/env_tools/build/bin:/usr/local/opt/node@12/bin:/usr/local/opt/mongodb-community@3.6/bin:/usr/local/bin:/Users/tian/Library/Android/sdk/platform-tools:/Users/tian/flutter/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Library/Apple/usr/bin:/Users/tian/Downloads/libs-build-tool/android/ndk-toolchain-arm-linux-androideabi/bin

INFO: AR /Users/tian/Downloads/libs-build-tool/android/ndk-toolchain-arm-linux-androideabi/bin/arm-linux-androideabi-ar

INFO: CC /Users/tian/Downloads/libs-build-tool/android/ndk-toolchain-arm-linux-androideabi/bin/arm-linux-androideabi-clang

INFO: CXX /Users/tian/Downloads/libs-build-tool/android/ndk-toolchain-arm-linux-androideabi/bin/arm-linux-androideabi-clang++

INFO: LD /Users/tian/Downloads/libs-build-tool/android/ndk-toolchain-arm-linux-androideabi/bin/arm-linux-androideabi-ld

INFO: RANLIB /Users/tian/Downloads/libs-build-tool/android/ndk-toolchain-arm-linux-androideabi/bin/arm-linux-androideabi-ranlib

INFO: STRIP /Users/tian/Downloads/libs-build-tool/android/ndk-toolchain-arm-linux-androideabi/bin/arm-linux-androideabi-strip

INFO: Target host arm-linux-androideabi

INFO: CFLAGS -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp  -std=c99 -Wno-unused-function -fno-integrated-as -fstrict-aliasing -fPIC -DANDROID -D__ANDROID__ -D__ANDROID_API__=21 -Os -ffunction-sections -fdata-sections  -I/Users/tian/Downloads/libs-build-tool/android/ndk-toolchain-arm-linux-androideabi/sysroot/usr/include -I/Users/tian/Downloads/libs-build-tool/android/ndk-toolchain-arm-linux-androideabi/sysroot/usr/local/include

INFO: CXXFLAGS -std=c++11 -fno-exceptions -fno-rtti -Os -ffunction-sections -fdata-sections

INFO: LDFLAGS -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -Wl,--fix-cortex-a8 -Wl,--gc-sections,--icf=safe -Os -ffunction-sections -fdata-sections -lc -lm -ldl -llog -L/Users/tian/Downloads/libs-build-tool/android/ndk-toolchain-arm-linux-androideabi/arm-linux-androideabi/lib -L/Users/tian/Downloads/libs-build-tool/android/ndk-toolchain-arm-linux-androideabi/sysroot/usr/lib -L/Users/tian/Downloads/libs-build-tool/android/ndk-toolchain-arm-linux-androideabi/lib -Wl,--hash-style=both -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libunwind.a

INFO: Init --prefix=/Users/tian/Downloads/libs-build-tool/prebuilt/arm-linux-androideabi

INFO: Init --arch-name=armeabi-v7a

INFO: Init --api=21

INFO: Init --host=arm-linux-androideabi

INFO: Guessing build system... armv7a-none-linux-android21

INFO: Packages licensing... GPL version 3

INFO: Creating configuration file... config.mak

INFO: Bootstrap completed.
    BUILD armv7a-none-linux-android21
    HOST arm-linux-androideabi
    PREFIX /Users/tian/Downloads/libs-build-tool/prebuilt/arm-linux-androideabi
    PKGS_ENABLE 
    PKGS_DISABLE 
    GPL 1
    GGNUV3PL 1
    AD_CLAUSES 
    ANDROID_ABI armeabi-v7a
    ANDROID_API 21

INFO: config.mak
     1	BUILD := armv7a-none-linux-android21
     2	HOST := arm-linux-androideabi
     3	PKGS_DISABLE := 
     4	PKGS_ENABLE := 
     5	PREFIX := /Users/tian/Downloads/libs-build-tool/prebuilt/arm-linux-androideabi
     6	GPL := 1
     7	GNUV3 := 1
     8	ANDROID_NDK := /Users/tian/Downloads/android-ndk-r18b
     9	ANDROID_ABI := armeabi-v7a
    10	ANDROID_API := 21
    11	HAVE_NEON := 1
    12	HAVE_ARMV7A := 1
    13	HAVE_LINUX := 1
    14	HAVE_ANDROID := 1
    15	PLATFORM_SHORT_ARCH := arm
    16	EXTRA_CFLAGS=-march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp  -std=c99 -Wno-unused-function -fno-integrated-as -fstrict-aliasing -fPIC -DANDROID -D__ANDROID__ -D__ANDROID_API__=21 -Os -ffunction-sections -fdata-sections  -I/Users/tian/Downloads/libs-build-tool/android/ndk-toolchain-arm-linux-androideabi/sysroot/usr/include -I/Users/tian/Downloads/libs-build-tool/android/ndk-toolchain-arm-linux-androideabi/sysroot/usr/local/include
    17	EXTRA_CXXFLAGS=-std=c++11 -fno-exceptions -fno-rtti -Os -ffunction-sections -fdata-sections
    18	EXTRA_LDFLAGS=-march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=softfp -Wl,--fix-cortex-a8 -Wl,--gc-sections,--icf=safe -Os -ffunction-sections -fdata-sections -lc -lm -ldl -llog -L/Users/tian/Downloads/libs-build-tool/android/ndk-toolchain-arm-linux-androideabi/arm-linux-androideabi/lib -L/Users/tian/Downloads/libs-build-tool/android/ndk-toolchain-arm-linux-androideabi/sysroot/usr/lib -L/Users/tian/Downloads/libs-build-tool/android/ndk-toolchain-arm-linux-androideabi/lib -Wl,--hash-style=both -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libunwind.a
    19	CC=/Users/tian/Downloads/libs-build-tool/android/ndk-toolchain-arm-linux-androideabi/bin/arm-linux-androideabi-clang
    20	CXX=/Users/tian/Downloads/libs-build-tool/android/ndk-toolchain-arm-linux-androideabi/bin/arm-linux-androideabi-clang++
    21	AR=/Users/tian/Downloads/libs-build-tool/android/ndk-toolchain-arm-linux-androideabi/bin/arm-linux-androideabi-ar
    22	RANLIB=/Users/tian/Downloads/libs-build-tool/android/ndk-toolchain-arm-linux-androideabi/bin/arm-linux-androideabi-ranlib
    23	LD=/Users/tian/Downloads/libs-build-tool/android/ndk-toolchain-arm-linux-androideabi/bin/arm-linux-androideabi-ld
    24	MAKE_FLAGS=-j4
    25	PREBUILT=/Users/tian/Downloads/libs-build-tool/prebuilt/arm-linux-androideabi
    26	FFMPEG_CONFIG=min

INFO: HOST is arm-linux-androideabi
INFO: BUILD is armv7a-none-linux-android21
make: Nothing to be done for `fetch'.
INFO: HOST is arm-linux-androideabi
INFO: BUILD is armv7a-none-linux-android21
INFO: PKGS_ALL All packages:
  ffmpeg gsm iconv lame libdsm libtasn1 openjpeg openssl zlib

INFO: PKGS_FOUND Distribution-provided packages:

INFO: PKGS_AUTOMATIC Automatically selected packages:
  ffmpeg iconv zlib

INFO: PKGS_DISABLE Manually deselected packages:

INFO: PKGS_MANUAL Manually selected packages:
  ffmpeg iconv zlib

INFO: PKGS_ENABLE Manually selected packages:

INFO: PKGS_DEPS Depended-on packages:

INFO: PKGS To-be-built packages:

INFO: HOST is arm-linux-androideabi
INFO: BUILD is armv7a-none-linux-android21
make: Nothing to be done for `all'.
INFO: Completed build for armeabi-v7a on API level 21 
```
没有看到编译...

**Comment by badboy-tian** [comment]
直接跑
```
./android.sh --enable-ffmpeg --ffmpeg-config-min --arch-armeabi-v7a
```
打印
```
INFO: /Users/tian/Downloads/android-ndk-r18b
INFO: /Users/tian/Library/Android/sdk
INFO: Architectures: 

INFO: Libraries: ffmpeg --ffmpeg-config-min --arch-armeabi-v7a 

INFO: Building env_tools

Unescaped left brace in regex is passed through in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at /Users/tian/Downloads/libs-build-tool/env_tools/build/bin/automake line 3936.
INFO: Completed env tools build

INFO: Help Info

INFO: You are ready to build libs
make: `.gas' is up to date.

```

如果使用ios跑, 没问题 正常编译
```
./ios.sh --enable-ffmpeg --ffmpeg-config-min --arch-arm64
```

**Comment by biezhihua** [comment]
@badboy-tian 请更新代码重新编译构建
